server:
  port: 8092

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    ##url: jdbc:postgresql://localhost:5432/grupocienciasbd
    ##url: jdbc:postgresql://192.190.42.193:5432/grupocienciasbd
    url: jdbc:postgresql://localhost:5432/ecobusbd
    username: postgres
    ##password: password
    password: 123456789